baseurl = "https://mboiman.github.io/"
languageCode = "en-us"
title = "Michael Boiman CV"
theme = "my-hugo-orbit-theme"
disableRSS = true
disableSitemap = true
disable404 = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[params]
description = "CV of Michael Boiman"
author = "Michael Boiman"
styles = "styles-6.css"

[params.profile]
name = "Michael Boiman"
tagline = "Full-Stack Dev & Quality Engineer – AI Automation Expert"
avatar = "profile.png"

[params.contact]
enable = true
[[params.contact.list]]
class = "email"
icon = "fa-envelope"
url = "mailto:mboiman@gmail.com"
title = "mboiman@gmail.com"

[[params.contact.list]]
class = "phone"
icon = "fa-phone"
url = ""
title = "Available on request via email"

[[params.contact.list]]
class = "website"
icon = "fa-globe"
url = "http://boiman-kupermann.com"
title = "BKS-Lab"

[[params.contact.list]]
class = "linkedin"
icon = "fa-linkedin"
url = "//linkedin.com/in/michael-boiman-ab709912"
title = "michael-boiman"

[[params.contact.list]]
class = "github"
icon = "fa-github"
url = "//github.com/bks-lab"
title = "GitHub Profile"

[[params.contact.list]]
class = "twitter"
icon = "fa-twitter"
url = "//twitter.com/mboiman"
title = "@mboiman"

[params.education]
enable = true
title = "Education"
[[params.education.list]]
degree = "Diploma in Computer Science (UAS)"
college = "Cologne University of Applied Sciences, Gummersbach"
dates = "2000 – 2005"

[[params.education.list]]
degree = "ISTQB Certified Tester"
dates = "2005"

[params.language]
enable = true
title = "Languages"
[[params.language.list]]
language = "German"
level = "Native"

[[params.language.list]]
language = "English"
level = "Professional"

[[params.language.list]]
language = "Russian"
level = "Conversational"

[[params.language.list]]
language = "Hebrew"
level = "Conversational"

[params.interests]
enable = false
title = "Interests"
[[params.interests.list]]
interest = "Gaming"

[[params.interests.list]]
interest = "Basketball"

[params.summary]
enable = true
icon = "fa-user"
title = "Career Profile"
summary = "With more than 20 years of experience in software development, I focus on automating business and quality processes and integrating artificial intelligence. My professional strengths include:\n- **AI Automation**: Optimising and implementing AI within existing business processes.\n- **Python Expertise**: Extensive experience in developing AI-based solutions, automations, and data analysis using Python.\n- **Business-Process Automation**: Increasing efficiency by automating manual workflows and data processing.\n- **Development of an AI Mail Bot**: Automated email processing and data synchronisation with third-party systems.\n- **Experience with LLMs**: GPT, Claude, Gemini, Llama, Mistral, RAGs, Agentic AI, MCP, A2A, among others.\n- **Test Automation**: Setting up quality gates within the CI/CD pipeline.\n- **Real-Time Monitoring**: Building systems that display quality status in real time.\n- **ML and DL Models**: Integrating machine-learning and deep-learning models into business processes.\n- **Performance Testing**: Conducting load and performance tests.\n- **Development**: Expertise in Java, JavaScript, Swift, Python and other languages.\n- **DevOps**: Experience with GitHub, GitLab, Jenkins and other CI/CD tools.\n- **Contract Testing**: Using Pact.io or Spring Contract.\n- **Cloud Technologies**: Proficient with Kubernetes, Helm, Terraform, ArgoCD, etc.\n- **Mobile Development**: Solid experience building mobile apps with Swift and Flutter.\n- **Agile Methods**: Practical application of Scrum and SAFe.\n- **Team Leadership**: Managing and coordinating cross-functional teams."

[params.experiences]
enable = true
icon = "fa-briefcase"
title = "Professional Experience"

[params.jobs]
[[params.jobs.list]]
position = "Quality Lead"
dates = "08/2021 – 05/2025"
company = "DVAG"
details = "**Test management & coordination**, as well as introduction of CI/CD with quality-gate setup. Acting as cross-team Quality Lead: onboarding, guidance, consulting and training for the introduction of quality metrics and test automation within the pipeline across teams.\n**Key responsibilities**\n- Design and implementation of functional and technical dashboards with Grafana for real-time quality measurement\n- Documentation of quality metrics covering the measurable sprint progress\n- Design and setup of CI/CD pipelines for multiple development teams (backend + frontend)\n- Introduction of quality gates to safeguard quality within the CI/CD pipeline\n- Adoption of Gauge (BDD)\n- Roll-out of Playwright and integration into the existing CI/CD pipeline\n- Functional and technical incident analysis\n- Consultancy, design and implementation of solutions for quality-related issues\n\n**Tools**\n- IntelliJ / Visual Studio Code\n- Java / JavaScript / TypeScript\n- Playwright / Gauge / Taiko / Karate\n- Python for processing and analysis of test and reporting data\n- CI/CD / GitHub – reusable workflows\n- Helm / Containers\n- JIRA / Confluence\n- Grafana\n- Behaviour-Driven Development\n- Consumer-Driven Contracts (Pact.io)\n        "

[[params.jobs.list]]
position = "Technical Lead & Development"
dates = "01/2024 – 04/2025"
company = "BKS"
details = "**Technical lead & development**: Design and implementation of a scalable automation solution for processing e‑invoices and PDF invoices fetched from a mailbox of a leading online job platform. Full responsibility from requirements analysis through implementation to production go‑live.\n\n**Focus areas**:\n- **Workflow automation**: Extraction, analysis and classification of incoming invoices using Python and Azure Functions.\n- **E‑invoice classification & data extraction**: Full processing in accordance with EU standard EN 16931 (ZUGFeRD, XRechnung), including structural and content parsing.\n- **Salesforce integration**: Forwarding prepared invoice data via email to the downstream system for Salesforce import.\n- **Auditing & logging**: Comprehensive documentation of all processing steps plus storage of original email content in the processing log.\n- **Outlook management & SharePoint archiving**: Automatic moving and categorising of emails into predefined Outlook folders; archiving of original and generated invoice documents via Microsoft Graph API.\n- **Monitoring & logging**: End‑to‑end real‑time monitoring with Kibana, including alerting and dashboard creation.\n- **Team coordination**: Managing the developer team incl. code reviews.\n\n**Tools & technologies**\n- Azure Functions: Serverless orchestration of automation workflows.\n- Python: Core logic for data extraction, classification and integration with automated CI/CD processes, packaging, and comprehensive unit and integration tests for quality assurance.\n- Microsoft Graph API: Access to Outlook mailboxes and SharePoint libraries.\n- GitHub: Version control, CI/CD pipelines and collaborative development.\n- Kibana: Monitoring, log analysis and performance dashboards.\n- Streamlit: For developing an interactive web application for visualization.\n        "

[[params.jobs.list]]
position = "Project Management & Technical Lead"
dates = "04/2023 - 04/2024"
company = "Ryze"
details = "**Project management & technical lead**: Development and deployment of an AI-driven email bot to automate customer communication, AI-assisted processing of incoming emails and triggering of follow-up activities in existing SAP systems. Responsible for end-to-end project coordination and team management from idea to implementation.\n\n**Focus areas**:\n- **Development of ML models**: Design and training of specialized models for effective email classification, implemented via Azure Functions.\n- **API integrations**: Seamless connection to Microsoft Outlook 365 via Microsoft Graph API and to SAP systems for customer data checks.\n- **Process automation**: Automatic moving of emails based on classification and specific business rules, including complaint handling.\n- **DevOps and monitoring**: Implementation of CI/CD pipelines and use of Kibana for monitoring.\n- **Development of a Streamlit-based user interface**: Improved testability and visualization of process results.\n- **Team coaching**: Technical guidance for developers with regular code reviews and problem-solving sessions.\n\n**Tools & technologies**\n- Azure Functions: For serverless application architectures and ML model execution.\n- Python: Main programming language for the email bot and ML models.\n- Microsoft Graph API: For accessing and processing emails in Microsoft Outlook 365.\n- SAP API: For querying customer data and communicating with SAP systems.\n- GitHub: For version control, CI/CD pipelines and collaborative development.\n- Kibana: For real-time monitoring and system performance analysis.\n- Streamlit: For developing an interactive web application for system monitoring.\n        "

[[params.jobs.list]]
position = "AI Workshop for Business Integration"
dates = "2023"
company = "Applications of AI in Business Context"
details = "**AI workshop**: Comprehensive presentation and live demonstration of innovative AI applications for business with a focus on practical implementation, theory and code examples.\n\n**Presentation content**\n- Comprehensive overview of AI fields and patterns (supervised/unsupervised/semi-supervised learning)\n- Deep dives into machine learning, deep learning and natural language processing\n- Detailed look at GPT models and their functionality (next token prediction)\n- Practical prompt engineering with examples for various use cases\n- Introduction to tools such as Hugging Face, Stable Diffusion, Midjourney and Auto-GPT\n\n**Practical workshop part**\n- Development of an intelligent Q&A bot with OpenAI GPT-3.5-Turbo\n- Live development of a web scraper for data acquisition\n- Extraction and vectorization of text embeddings with OpenAI models\n- Implementation of similarity search for context-based answers\n- Similarity analysis and visualization of results\n- Creation of an interactive Streamlit user interface for the Q&A bot\n\n**Technologies used**\n- OpenAI API (GPT-3.5-Turbo, Embedding-Ada-002)\n- Python with Pandas, NumPy and Streamlit\n- Vector embeddings and cosine similarity for semantic search\n- Web scraping with BeautifulSoup and Requests\n- Prompt engineering and AI integration into business processes\n- Integration via RESTful APIs\n\nThe full presentation is available at [Pitch.com](https://pitch.com/public/bc7eaebb-5fb1-4e6f-bf84-ce9363c7abc0). The complete source code of the developed Q&A bot is documented in my [GitHub repository](https://github.com/boiman-solutions/workshop-q-a-scrap-bot).\n        "

[[params.jobs.list]]
position = "Senior iOS Developer"
dates = "04/2015 - 09/2015"
company = "Telekom"
details = "**Senior iOS Developer**: Further development of the rebuilt version of Deutsche Telekom's **Customer Center App**, extension with new functionalities for IFA.\n**Key responsibilities**\n- Swift\n- iOS 8\n- Requests & responses to backend\n- Error handling\n- iPad / iPhone\n- Scrum\n\n**Tools**\n- Xcode\n- Git\n- JIRA\n        "

[[params.jobs.list]]
position = "QA, Test Management"
dates = "05/2009 - 03/2015"
company = "Siemens"
details = "**QA, test management, test automation, requirements engineering**: A total of 5 projects were supported as QA & test manager and successfully implemented\n**Projects**\n- SIPCA - Management system for employee annual targets and bonus calculation\n- STM - Application and travel expense recording (Frontend: Web / Backend: SAP)\n- GPM2 - Share bonus program for employees (Frontend: Web / Backend: JBoss)\n- PATAC\n- SOM - Management and overview of OrgUnits\n\n**Key responsibilities**\n- Creation of technical test concepts and test plans\n- Defect tracking\n- Management of CRs, communication between customers and developers\n- Creation, maintenance and scheduling of test automation\n- User acceptance tests\n- Training of new testers and test automation engineers\n- Support as test manager after project completion in regular operation\n- Setup of acceptance tests\n- Transfer of functional specification and detailed specification to Quality Center\n- Monitoring of implemented requirements against the detailed concept\n\n**Tools**\n- HP ALM\n- HP UFT\n- HP QC\n- Quick Test Pro\n        "

[[params.jobs.list]]
position = "Load and Performance Tester"
dates = "03/2009 - 05/2009"
company = "ING-DIBA"
details = "**Load and performance tester**: The goal of the project is the design and development of LoadRunner scripts for load testing a bundle of approx. 20 J2EE applications in a banking portal\n**Key responsibilities**\n- Creation of test scripts in LoadRunner with the http protocol\n- Execution of load tests and analysis of results\n- Monitoring and reporting\n\n**Tools**\n- LoadRunner\n        "

[[params.jobs.list]]
position = "Summary of Various Activities"
dates = "01/2006 - 12/2008"
company = "British Telecom, Mobiliar, DB-Systel, Sparkassen Informatik, Loyalty Partner, Telekom, Itelium, Deutsche Post, Postbank"
details = "**Load and performance tester / tester**: Various projects, predominantly load & performance tests\n**Key responsibilities**\n- Creation of test scripts in LoadRunner with the http protocol\n- Execution of load tests and analysis of results\n- Monitoring and reporting\n\n**Tools**\n- LoadRunner\n        "

[params.projects]
enable = true
icon = "fa-archive"
title = "PROJECTS"
intro = "**Additional projects outside the core business**"
[[params.projects.list]]
title = "wecation"
url = "https://www.wecation.de"
tagline = "wecation is a collaborative solution for organising shared experiences: plan, search, coordinate with friends or colleagues and enjoy the activity together!"

[[params.projects.list]]
title = "QualityCluster"
url = "https://qualitycluster.de"
tagline = "QualityCluster is an alliance of quality engineers jointly developing better solutions in software quality assurance.\nOur goal is to implement more quality through a higher degree of automation.  \n"

[[params.projects.list]]
title = "AI-Driven Chatbot for Trade-Fair Interaction"
url = "#"
tagline = "Development of an interactive chatbot using RAG and OpenAI to optimise user interaction on a trade-fair website."

[[params.projects.list]]
title = "Automated NLP Analysis of PDF Documents"
url = "#"
tagline = "Using NLP technologies to boost efficiency in automated document analysis."

[[params.projects.list]]
title = "Email Classification and Processing Workflow"
url = "#"
tagline = "Integration of Microsoft Graph API, SAP, Azure Functions, REST API, OpenAI, Elasticsearch and Kibana to optimise email processing."

[[params.projects.list]]
title = "MCP – Model Context Protocol"
url = "#"
tagline = "Implementation of various tools for model-context orchestration."

[[params.projects.list]]
title = "AI Automation Function Modules"
url = "#"
tagline = "Building function modules for faster rollout of AI automation."

[[params.projects.list]]
title = "AI Consulting for Enterprises"
url = "#"
tagline = "Consultancy on the use of AI within companies."

[params.skills]
enable = true
icon = "fa-rocket"
title = "SKILLS & TOOLS"
[[params.skills.list]]
skill = "Python (Data Analysis, ML/AI, Automation)"
level = "98%"

[[params.skills.list]]
skill = "AI & Machine Learning"
level = "96%"

[[params.skills.list]]
skill = "Software Development, Design, Architecture"
level = "99%"

[[params.skills.list]]
skill = "JIRA & Confluence"
level = "98%"

[[params.skills.list]]
skill = "IntelliJ & VS Code"
level = "93%"

[[params.skills.list]]
skill = "Playwright"
level = "97%"

[[params.skills.list]]
skill = "Cucumber / Gauge / Taiko"
level = "99%"

[[params.skills.list]]
skill = "CDC – Spring Contract & Pact.io"
level = "70%"

[[params.skills.list]]
skill = "CI/CD Workflows – GitLab, GitHub & Jenkins"
level = "90%"

[[params.skills.list]]
skill = "Kubernetes – Helm, Terraform & ArgoCD"
level = "80%"

[[params.skills.list]]
skill = "REST & Postman"
level = "95%"

[[params.skills.list]]
skill = "Load & Performance Testing with JMeter, Gatling"
level = "90%"

[[params.skills.list]]
skill = "AWS, Google Cloud & Azure"
level = "80%"

[[params.skills.list]]
skill = "Dashboards & Analytics –\nKibana (+ES) & Graylog &  \nGrafana & Instana\n        "
level = "90%"

[[params.skills.list]]
skill = "Mobile Dev – Xcode, Flutter & Swift"
level = "90%"

