# Page settings (Deutsches CV)

# Die Basiseinstellungen werden aus config.yaml gelesen

[params]

# Meta
    description = "Lebenslauf von Michael Boiman"
    author = "Michael Boiman"

# Theme styles
    styles = "styles-6.css"

# ───────────────────────  Sidebar sections  ────────────────────────

    # Profile section
    [params.profile]
        name = "Michael Boiman"
        tagline = "Full-Stack Dev & Quality Engineer – KI-Automatisierungsexperte"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto:mboiman@gmail.com"
        title = "mboiman@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = ""
        title = "Auf Anfrage per E-Mail verfügbar"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "http://boiman-kupermann.com"
        title = "BKS-Lab"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/michael-boiman-ab709912"
        title = "michael-boiman"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/bks-lab"
        title = "GitHub Profil"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/mboiman"
        title = "@mboiman"

    # Education section
    [params.education]
        enable = true
        title = "Ausbildung"

        [[params.education.list]]
        degree = "Diplom-Informatiker (FH)"
        college = "Fachhochschule Köln, Gummersbach"
        dates = "2000 – 2005"

        [[params.education.list]]
        degree = "ISTQB Certified Tester"
        dates = "2005"

    # Languages section
    [params.language]
        enable = true
        title = "Sprachen"

        [[params.language.list]]
        language = "Deutsch"
        level = "Muttersprache"

        [[params.language.list]]
        language = "Englisch"
        level = "Fließend"

        [[params.language.list]]
        language = "Russisch"
        level = "Konversationslevel"

        [[params.language.list]]
        language = "Hebräisch"
        level = "Konversationslevel"

    # Interests section
    [params.interests]
        enable = false
        title = "Interessen"

        [[params.interests.list]]
        interest = "Gaming"

        [[params.interests.list]]
        interest = "Basketball"

# ─────────────────────  Main body sections  ────────────────────────

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Profil"
        summary = """\
Mit mehr als 20 Jahren Erfahrung in der Softwareentwicklung liegt mein Fokus auf der Automatisierung von Geschäfts- und Qualitätsprozessen sowie der Integration künstlicher Intelligenz. Zu meinen fachlichen Schwerpunkten zählen:
- **KI-Automatisierung**: Optimierung und Implementierung von KI in bestehende Geschäftsprozesse.
- **Geschäftsprozess-Automatisierung**: Effizienzsteigerung durch Automatisierung manueller Abläufe und Datenverarbeitung.
- **Entwicklung eines KI-Mail-Bots**: Automatisierte E-Mail-Verarbeitung und Datenabgleich mit Drittsystemen.
- **Erfahrung mit LLMs**: Einsatz von GPT, Claude, Gemini, Llama, Mistral, RAGs, Agentic AI, MCP, A2A u.a.
- **Testautomatisierung**: Einrichtung von Quality-Gates innerhalb der CI/CD-Pipeline.
- **Echtzeit-Monitoring**: Entwicklung von Systemen zur Darstellung des Qualitätsstands in Echtzeit.
- **ML und DL-Modelle**: Integration von Machine Learning und Deep Learning in Geschäftsprozesse.
- **Performance-Tests**: Durchführung von Last- und Performance-Tests.
- **Entwicklung**: Expertise in Java, JavaScript, Swift, Python und weiteren Sprachen.
- **DevOps**: Erfahrung mit GitHub, GitLab, Jenkins und anderen CI/CD-Tools.
- **Contract-Testing**: Anwendung von Pact.io oder Spring Contract.
- **Cloud-Technologien**: Kenntnisse in Kubernetes, Helm, Terraform, ArgoCD u.a.
- **Mobile Entwicklung**: Fundierte Erfahrungen in der Entwicklung mobiler Anwendungen mit Swift und Flutter.
- **Agile Methoden**: Praktische Anwendung von Scrum und SAFE.
- **Teamleitung**: Leitung und Koordination von interdisziplinären Teams.
"""

# ─────────────────── Experiences section ───────────────────────────

    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Berufserfahrung"

        [[params.jobs.list]]
        position = "Quality Lead"
        dates = "08/2021 – 05/2025"
        company = "DVAG"
        details = """
**Testmanagement & Testkoordination**, sowie Einführung von CICD mit Aufbau von QualityGates** Koordination als Quality-Lead (übergreifendes QA-Team) inklusive Einarbeitung, Hilfestellung, Beratung, Schulung zur Einführung von Qualitätsmetriken und Testautomatisierung innerhalb der Pipeline, Teamübergreifend 
**Schwerpunkte** 
- Konzeption und Aufbau vom fachlichen und technischen Dashboards mit Grafana zur Echtzeitmessung der Qualität 
- Dokumentation von Qualitätsmetriken über Fortschritt der messbaren Qualität der Sprints 
- Aufbau und Konzeption einer CICD-Pipeline für verschiedene Entwicklungs-Teams (Backend + Frontend) 
- Einführung von QualityGates zur Sicherung der Qualität innerhalb der CICD-Pipeline
- Einführung von Gauge (BDD) 
- Einführung von Playwright und Integration in bestehende CICD-Pipeline
- Fachliche und technische Analyse von Incidents 
- Beratung sowie Konzeption und Umsetzung von Lösungen für qualitäts-relevante Probleme 

**Tools** 
- IntelliJ / Visual Studio Code 
- Java / Java-Script / Typescript 
- Playwright / Gauge / Taiko / Karate 
- CI/CD / Github – reuseable workflows 
- Helm / Container 
- JIRA / Confluence 
- Grafana 
- Behavioral-Driven Development 
- Consumer Driven Contracts (Pact.io) 
"""

        [[params.jobs.list]]
        position = "Technische Leitung & Entwicklung"
        dates = "12/2023 – 04/2024"
        company = "StepStone"
        details = """
**Technische Leitung & Entwicklung**: Konzeption und Umsetzung einer skalierbaren Automatisierungslösung für die Verarbeitung von E-Rechnungen und PDF-Rechnungen aus dem Postfach einer führenden Online-Jobplattform. Vollständige Verantwortung von der Anforderungsanalyse über die Implementierung bis zur Produktionseinführung.

**Schwerpunkte**:
- **Workflow-Automatisierung**: Extraktion, Analyse und Klassifizierung eingehender Rechnungen mittels Python und Azure Functions.
- **E-Rechnungs-Klassifizierung & Daten-Extraction**: Vollständige Verarbeitung nach EU-Standards (EN 16931: ZUGFeRD, XRechnung), inklusive Struktur- und Inhalts-Parsing.
- **Salesforce-Einspielung**: Weiterleitung der aufbereiteten Rechnungsdaten per E-Mail an das nachgelagerte System für den Salesforce-Import.
- **Auditierung & Protokollierung**: Lückenlose Dokumentation aller Verarbeitungsschritte sowie Speicherung der ursprünglichen E-Mail-Inhalte im Verarbeitungsprotokoll.
- **Outlook-Management & SharePoint-Archivierung**: Automatisches Verschieben und Kategorisieren von E-Mails in vordefinierte Zielordner in Outlook; Archivierung von Original- und generierten Rechnungsdokumenten über Microsoft Graph API.
- **Monitoring & Logging**: Echtzeit-Überwachung des End-to-End-Prozesses mit Kibana, inklusive Alerting und Dashboard-Erstellung.
- **Team-Koordination**: Steuerung des Entwickler-Teams inkl. Code-Reviews.

**Tools & Technologien**
- Azure Functions: Serverlose Orchestrierung der Automatisierungs-Workflows.
- Python: Implementierung der Kernlogik für Datenextraktion, Klassifizierung und Integration.
- Microsoft Graph API: Zugriff auf Outlook-Postfächer und SharePoint-Dokumentbibliotheken.
- GitHub: Versionskontrolle, CI/CD-Pipelines und kollaborative Entwicklung.
- Kibana: Monitoring, Log-Analyse und Performance-Dashboards.
"""
