baseurl = "https://mboiman.github.io/"
languageCode = "de-de"
title = "Michael Boiman CV"
theme = "my-hugo-orbit-theme"
disableRSS = true
disableSitemap = true
disable404 = true
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true

[params]
description = "Lebenslauf von Michael Boiman"
author = "Michael Boiman"
styles = "styles-6.css"

[params.profile]
name = "Michael Boiman"
tagline = "Testautomatisierungs‑Spezialist (Playwright & Gauge) | Full‑Stack Developer"
avatar = "profile.png"

[params.contact]
enable = true
[[params.contact.list]]
class = "email"
icon = "fa-envelope"
url = "mailto:mboiman@gmail.com"
title = "mboiman@gmail.com"

[[params.contact.list]]
class = "phone"
icon = "fa-phone"
url = ""
title = "Auf Anfrage per E-Mail verfügbar"

[[params.contact.list]]
class = "website"
icon = "fa-globe"
url = "http://boiman-kupermann.com"
title = "BKS-Lab"

[[params.contact.list]]
class = "linkedin"
icon = "fa-linkedin"
url = "//linkedin.com/in/michael-boiman-ab709912"
title = "michael-boiman"

[[params.contact.list]]
class = "github"
icon = "fa-github"
url = "//github.com/mboiman"
title = "GitHub Profil"

[[params.contact.list]]
class = "twitter"
icon = "fa-twitter"
url = "//twitter.com/mboiman"
title = "@mboiman"

[params.education]
enable = true
title = "Ausbildung"
[[params.education.list]]
degree = "Diplom-Informatiker (FH)"
college = "Fachhochschule Köln, Gummersbach"
dates = "2000 – 2005"

[[params.education.list]]
degree = "ISTQB Certified Tester"
dates = "2005"

[params.language]
enable = true
title = "Sprachen"
[[params.language.list]]
language = "Deutsch"
level = "Muttersprache"

[[params.language.list]]
language = "Englisch"
level = "Fließend"

[[params.language.list]]
language = "Russisch"
level = "Konversationslevel"

[[params.language.list]]
language = "Hebräisch"
level = "Konversationslevel"

[params.summary]
enable = true
icon = "fa-user"
title = "Karriereprofil"
summary = """\
Über 20 Jahre Erfahrung in der Software‑Entwicklung, Quality Engineering und KI‑getriebenen Automatisierungen.
Meine Schwerpunkte:
- **Testautomatisierung & BDD**: End‑to‑End‑ und Integrations‑Tests mit **Playwright**; szenarien­basiertes Testing mit **Gauge/Cucumber**; Aufbau von **QualityGates** in CI/CD‑Pipelines (GitHub, GitLab, Jenkins).
- **CI/CD‑Dashboards**: Echtzeit‑Monitoring der Code‑Qualität mit **Grafana, Kibana, Instana** inkl. automatischem Reporting.
- **KI‑Automatisierung**: GPT‑gestützte Workflows (E‑Mail‑Bots, NLP‑Pipelines) zur Effizienz­steigerung.
- **Python‑Expertise**: Datenanalyse, Skripting und Automatisierung (Azure Functions, Streamlit).
- **Performance‑ & Lasttests**: JMeter, Gatling; Analyse & Visualisierung der Ergebnisse.
- **Cloud‑Technologien**: Azure Functions, Kubernetes, Helm, Terraform, ArgoCD.
- **Agile Leadership**: Scrum/SAFe, Coaching interdisziplinärer Teams.\n"""

[params.experiences]
enable = true
icon = "fa-briefcase"
title = "Berufserfahrung"

[params.jobs]
[[params.jobs.list]]
position = "Quality Lead"
dates = "08/2021 – 05/2025"
company = "DVAG"
details = """**Testmanagement & Testkoordination** – Aufbau einer konzernweiten CI/CD‑Pipeline mit QualityGates.
- Einführung von **Playwright**‑basierten UI‑Tests & Gauge (BDD) in GitHub Actions  
- Grafana‑Dashboards zur Sprint‑Qualitäts­messung  
- Incident‑Analyse, QA‑Schulungen, Coaching des Dev‑Teams  
"""

[[params.jobs.list]]
position = "Technische Leitung & Entwicklung"
dates = "01/2024 – 04/2025"
company = "BKS"
details = """Konzeption und Umsetzung einer serverlosen Automatisierung zur Verarbeitung von E‑Rechnungen (Python, Azure Functions).
- KI‑basierte Klassifizierung & Validierung (ZUGFeRD, XRechnung)  
- Vollständige Testabdeckung in CI/CD, Monitoring mit Kibana"""

[[params.jobs.list]]
position = "Technische Leitung & Entwicklung"
dates = "04/2023 – 04/2024"
company = "Ryze"
details = """Entwicklung eines GPT‑gestützten E‑Mail‑Bots zur Automatisierung der Kunden­kommunikation.
- Azure Functions, Microsoft Graph API, SAP‑Anbindung  
- Kibana‑Dashboards, GitHub CI/CD  
- Team‑Leitung & Code‑Reviews"""

[[params.jobs.list]]
position = "Anwendungen von KI im Geschäftsumfeld (Workshop)"
dates = "2023"
company = "Freelance"
details = """Entwicklung & Live‑Demo eines Q&A‑Bots mit OpenAI GPT‑3.5‑Turbo und Streamlit.
- Web‑Scraping, Embeddings, Similarity Search  
- Prompt Engineering, Deployment auf Azure"""

[[params.jobs.list]]
position = "Quality Lead"
dates = "01/2017 – 05/2021"
company = "DB Vertrieb" 
details = """Agile QA (Scrum/SAFe) – Konzeption von QualityGates in CI/CD; Performance‑Tests mit Gatling & JMeter; BDD mit Cucumber."""

[[params.jobs.list]]
position = "Load & Performance Tests"
dates = "09/2015 – 01/2017"
company = "DB Systel"
details = """Aufbau und Durchführung umfassender Performance‑Tests (JMeter); Analyse & Reporting. """

[[params.jobs.list]]
position = "Senior iOS Developer"
dates = "04/2015 – 09/2015"
company = "Telekom"
details = """Weiterentwicklung der Kundencenter‑App (Swift, iOS 8, Scrum‑Setup)."""

[[params.jobs.list]]
position = "QS, Testmanagement"
dates = "05/2009 – 03/2015"
company = "Siemens"
details = """Leitung von fünf QA‑Projekten; Aufbau automatisierter Tests mit HP UFT & Quality Center."""

[[params.jobs.list]]
position = "Last & Performance Tester"
dates = "03/2009 – 05/2009"
company = "ING‑DIBA"
details = """Konzeption & Entwicklung von LoadRunner‑Skripten für ein J2EE‑Bankportal."""

[[params.jobs.list]]
position = "Diverse Performance‑Testprojekte"
dates = "01/2006 – 12/2008"
company = "Mehrere Kunden"
details = """Last‑ & Performance‑Tests (LoadRunner) für Telekommunikations‑ und Finanz­dienstleister."""

[params.projects]
enable = true
icon = "fa-archive"
title = "NEBENPROJEKTE"
intro = "**Weitere Projekte außerhalb des Kerngeschäfts**"

[[params.projects.list]]
title = "wecation"
url = "https://www.wecation.de"
tagline = "Kollaborative Lösung zur Erlebnis‑Organisation."

[[params.projects.list]]
title = "QualityCluster"
url = "https://qualitycluster.de"
tagline = "Community von Quality Engineers zur Förderung von Testautomatisierung."

[[params.projects.list]]
title = "KI‑basierter Chatbot für Messe‑Interaktion"
url = "#"
tagline = "RAG + OpenAI zur Optimierung der Besucher­interaktion."

[[params.projects.list]]
title = "Automatisierte NLP‑Analyse von PDF‑Dokumenten"
url = "#"
tagline = "NLP‑Technologien zur Effizienzsteigerung."

[[params.projects.list]]
title = "E‑Mail‑Klassifizierung & ‑Verarbeitung"
url = "#"
tagline = "Azure Functions + Microsoft Graph API."

[[params.projects.list]]
title = "MCP – Model Context Protocol"
url = "#"
tagline = "Tools zur Modell‑Kontext‑Orchestrierung."

[[params.projects.list]]
title = "AI‑Automatisierungs‑Functionsbausteine"
url = "#"
tagline = "Functions‑Bausteine für schnelle AI‑Einführung."

[[params.projects.list]]
title = "AI‑Beratung für Unternehmen"
url = "#"
tagline = "Strategische Beratung zum AI‑Einsatz."

[params.skills]
enable = true
icon = "fa-rocket"
title = "Skills & Tools"

[[params.skills.list]]
skill = "Playwright"
level = "97%"

[[params.skills.list]]
skill = "Gauge / Cucumber / Taiko"
level = "99%"

[[params.skills.list]]
skill = "CI/CD‑Workflows – GitHub, GitLab, Jenkins"
level = "90%"

[[params.skills.list]]
skill = "Grafana, Kibana, Instana"
level = "90%"

[[params.skills.list]]
skill = "Python (Automatisierung, ML/AI)"
level = "98%"

[[params.skills.list]]
skill = "AI & Machine Learning"
level = "96%"

[[params.skills.list]]
skill = "Software‑Entwicklung, ‑Design, ‑Architektur"
level = "99%"

[[params.skills.list]]
skill = "Jira & Confluence"
level = "98%"

[[params.skills.list]]
skill = "IntelliJ & VS Code"
level = "93%"

[[params.skills.list]]
skill = "CDC – Spring Contract & Pact.io"
level = "70%"

[[params.skills.list]]
skill = "Kubernetes, Helm, Terraform, ArgoCD"
level = "80%"

[[params.skills.list]]
skill = "REST & Postman"
level = "95%"

[[params.skills.list]]
skill = "Last‑ & Performance‑Testing – JMeter, Gatling"
level = "90%"

[[params.skills.list]]
skill = "Cloud – AWS, Google, Azure"
level = "80%"

[[params.skills.list]]
skill = "Mobile‑Entwicklung – Swift, Flutter"
level = "90%"

[params.footer]
copyright = "Michael.Boiman"
