# Example overrides for a custom CV

defaultContentLanguage = "de"

[languages.de.params.profile]
name = "Max Mustermann"
tagline = "Individuell angepasstes Profil"

[languages.de.params.summary]
summary = "Kurzprofil für eine bestimmte Bewerbung."

[languages.de.params.contact]
enable = false

[languages.en.params.profile]
name = "John Doe"
tagline = "Customized profile for the request"
