# English Language Configuration
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages.en]
  languageCode = "en-us"
  languageName = "English"
  title = "Michael Boiman CV"
  contentDir = "content/en"
  weight = 1

  [languages.en.params]
    description = "CV of Michael Boiman"
    author = "Michael Boiman"
    
    [languages.en.params.profile]
      name = "Michael Boiman"
      tagline = "Full-Stack Dev & Quality Engineer – AI Automation Expert"
      avatar = "profile.png"

    [languages.en.params.contact]
      enable = true

      [[languages.en.params.contact.list]]
      class = "email"
      icon = "fa-envelope"
      url = "mailto:mboiman@gmail.com"
      title = "mboiman@gmail.com"

      [[languages.en.params.contact.list]]
      class = "phone"
      icon = "fa-phone"
      url = ""
      title = "Available on request via email"

      [[languages.en.params.contact.list]]
      class = "website"
      icon = "fa-globe"
      url = "http://boiman-kupermann.com"
      title = "BKS-Lab"

      [[languages.en.params.contact.list]]
      class = "linkedin"
      icon = "fa-linkedin"
      url = "//linkedin.com/in/michael-boiman-ab709912"
      title = "michael-boiman"

      [[languages.en.params.contact.list]]
      class = "github"
      icon = "fa-github"
      url = "//github.com/bks-lab"
      title = "GitHub Profile"

    [languages.en.params.skills]
      enable = true
      icon = "fa-rocket"
      title = "SKILLS & TOOLS"

      [[languages.en.params.skills.list]]
      skill = "Python (Data Analysis, ML/AI, Automation)"
      level = "98%"
      
      [[languages.en.params.skills.list]]
      skill = "AI & Machine Learning"
      level = "96%"
      
      [[languages.en.params.skills.list]]
      skill = "Software Development, Design, Architecture"
      level = "99%"

      [[languages.en.params.skills.list]]
      skill = "Playwright"
      level = "97%"

      [[languages.en.params.skills.list]]
      skill = "CI/CD Workflows – GitLab, GitHub & Jenkins"
      level = "90%"

      [[languages.en.params.skills.list]]
      skill = "Kubernetes – Helm, Terraform & ArgoCD"
      level = "80%"